.TH "mtrx::mtrxDynamicWorld" 3 "Sat Dec 7 2019" "MTRX Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtrx::mtrxDynamicWorld \- Entry point of the user to the engine\&. This class defines the API that user will be using to interface with the engine\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mtrxDynamicWorld\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmtrxDynamicWorld\fP ()"
.br
.RI "Construct a new mtrx Dynamic World object\&. "
.ti -1c
.RI "\fB~mtrxDynamicWorld\fP ()=default"
.br
.RI "Destroy the mtrx Dynamic World object\&. "
.ti -1c
.RI "void \fBUpdate\fP (float dt)"
.br
.RI "Update the game world\&. "
.ti -1c
.RI "void \fBAddRigidbody\fP (\fBRigidbody\fP *rb)"
.br
.RI "Add a rigidbody to the rigidbody manager\&. "
.ti -1c
.RI "void \fBRemoveRigidbody\fP (\fBRigidbody\fP *rb)"
.br
.RI "Remove a rigidbody from the rigidbody manager\&. "
.ti -1c
.RI "void \fBAddForceGenerator\fP (\fBRigidbody\fP *rb, const std::shared_ptr< \fBIRigidbodyForceGenerator\fP > &forceGenerator)"
.br
.RI "Add a force generator to the rigidbody manager\&. "
.ti -1c
.RI "void \fBRemoveForceGenerator\fP (\fBRigidbody\fP *rb, const std::shared_ptr< \fBIRigidbodyForceGenerator\fP > &generator)"
.br
.RI "Remove a rigidbody from the rigidbody manager\&. "
.ti -1c
.RI "void \fBAddCollider\fP (\fBCollider\fP *col)"
.br
.RI "Add a collider to the collision system\&. "
.ti -1c
.RI "void \fBRemoveCollider\fP (\fBCollider\fP *col)"
.br
.RI "Remove a collider to the collision system\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBaccumulator\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBRigidbodyManager\fP \fBm_rbManager\fP"
.br
.ti -1c
.RI "\fBCollisionSystem\fP \fBm_CollisionSystem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Entry point of the user to the engine\&. This class defines the API that user will be using to interface with the engine\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "mtrx::mtrxDynamicWorld::mtrxDynamicWorld ()"

.PP
Construct a new mtrx Dynamic World object\&. 
.SS "mtrx::mtrxDynamicWorld::~mtrxDynamicWorld ()\fC [default]\fP"

.PP
Destroy the mtrx Dynamic World object\&. 
.SH "Member Function Documentation"
.PP 
.SS "void mtrx::mtrxDynamicWorld::AddCollider (\fBCollider\fP * col)\fC [inline]\fP"

.PP
Add a collider to the collision system\&. 
.PP
\fBParameters\fP
.RS 4
\fIcol\fP The collider that we want to add 
.RE
.PP

.SS "void mtrx::mtrxDynamicWorld::AddForceGenerator (\fBRigidbody\fP * rb, const std::shared_ptr< \fBIRigidbodyForceGenerator\fP > & forceGenerator)\fC [inline]\fP"

.PP
Add a force generator to the rigidbody manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIrb\fP The rigidbody we want to add the force generator to 
.br
\fIforceGenerator\fP The force generator we want to add 
.RE
.PP

.SS "void mtrx::mtrxDynamicWorld::AddRigidbody (\fBRigidbody\fP * rb)\fC [inline]\fP"

.PP
Add a rigidbody to the rigidbody manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIrb\fP The rigidbody we want to add to the manager 
.RE
.PP

.SS "void mtrx::mtrxDynamicWorld::RemoveCollider (\fBCollider\fP * col)\fC [inline]\fP"

.PP
Remove a collider to the collision system\&. 
.PP
\fBParameters\fP
.RS 4
\fIcol\fP The collider that we want to remove 
.RE
.PP

.SS "void mtrx::mtrxDynamicWorld::RemoveForceGenerator (\fBRigidbody\fP * rb, const std::shared_ptr< \fBIRigidbodyForceGenerator\fP > & generator)\fC [inline]\fP"

.PP
Remove a rigidbody from the rigidbody manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIrb\fP The rigidbody we want to remove the rigidbody from 
.br
\fIgenerator\fP The force generator that we want to remove 
.RE
.PP

.SS "void mtrx::mtrxDynamicWorld::RemoveRigidbody (\fBRigidbody\fP * rb)\fC [inline]\fP"

.PP
Remove a rigidbody from the rigidbody manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIrb\fP The rigidbody we want to remove 
.RE
.PP

.SS "void mtrx::mtrxDynamicWorld::Update (float dt)"

.PP
Update the game world\&. 
.PP
\fBParameters\fP
.RS 4
\fIdt\fP The time elapsed since the last frame 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MTRX Engine from the source code\&.
