.TH "mtrx::rb_GravityForceGenerator" 3 "Sat Dec 7 2019" "MTRX Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtrx::rb_GravityForceGenerator \- Implementation of gravitational force generator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rb_GravityForceGenerator\&.h>\fP
.PP
Inherits \fBmtrx::IRigidbodyForceGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBUpdateForces\fP (\fBRigidbody\fP *rb, float deltaTime)"
.br
.RI "Implementation of the force generator\&. "
.ti -1c
.RI "\fBrb_GravityForceGenerator\fP (const glm::vec3 &gravity)"
.br
.RI "Construct a new rb GravityForceGenerator object\&. "
.ti -1c
.RI "\fB~rb_GravityForceGenerator\fP ()"
.br
.RI "Destroy the rb GravityForceGenerator object\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBgravitationalAcceleration\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of gravitational force generator\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "mtrx::rb_GravityForceGenerator::rb_GravityForceGenerator (const glm::vec3 & gravity)"

.PP
Construct a new rb GravityForceGenerator object\&. 
.PP
\fBParameters\fP
.RS 4
\fIgravity\fP The gravitational acceleration value that we want to use 
.RE
.PP

.SS "mtrx::rb_GravityForceGenerator::~rb_GravityForceGenerator ()"

.PP
Destroy the rb GravityForceGenerator object\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual void mtrx::rb_GravityForceGenerator::UpdateForces (\fBRigidbody\fP * rb, float deltaTime)\fC [virtual]\fP"

.PP
Implementation of the force generator\&. 
.PP
\fBParameters\fP
.RS 4
\fIrb\fP The rigidbody to apply the force onto 
.br
\fIdeltaTime\fP The time elapsed since the last frame 
.RE
.PP

.PP
Implements \fBmtrx::IRigidbodyForceGenerator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MTRX Engine from the source code\&.
