.TH "mtrx::ColliderDetectionUtil" 3 "Sat Dec 7 2019" "MTRX Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtrx::ColliderDetectionUtil \- Utility namespace used for resolving collision detection algorithms to be used based on collider types\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBCollide\fP (const \fBCollider\fP &collider1, const \fBCollider\fP &collider2)"
.br
.RI "Check for whether 2 colliders collide\&. "
.ti -1c
.RI "bool \fBSphereCollisionOptions\fP (const \fBSphereCollider\fP &sphCollider, const \fBCollider\fP &collider)"
.br
.RI "Collision algorithm options for sphere colliders\&. "
.ti -1c
.RI "bool \fBAABBCollisionOptions\fP (const \fBAABBCollider\fP &aabb, const \fBCollider\fP &collider)"
.br
.RI "Collision algorithm options for AABB colliders\&. "
.ti -1c
.RI "bool \fBOOBBCollisionOptions\fP (const \fBOOBBCollider\fP &oobb, const \fBCollider\fP &collider)"
.br
.RI "Collision algorithm options for OOBB colliders\&. "
.ti -1c
.RI "bool \fBCapsuleCollisionOptions\fP (const \fBCapsuleCollider\fP &capCollider, const \fBCollider\fP &collider)"
.br
.RI "Collision algorithm options for capsule colliders @mtrx::CapsuleCollider\&. "
.ti -1c
.RI "bool \fBConvexShapeCollisionOptions\fP (const \fBConvexShapeCollider\fP &convexCollider, const \fBCollider\fP &collider)"
.br
.RI "Collision algotithm options for convex shape colliders\&. "
.in -1c
.SH "Detailed Description"
.PP 
Utility namespace used for resolving collision detection algorithms to be used based on collider types\&. 


.PP
\fBSee also\fP
.RS 4
\fBmtrx::ColliderType\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "bool mtrx::ColliderDetectionUtil::AABBCollisionOptions (const \fBAABBCollider\fP & aabb, const \fBCollider\fP & collider)"

.PP
Collision algorithm options for AABB colliders\&. 
.PP
\fBSee also\fP
.RS 4
\fBmtrx::AABBCollider\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fIaabb\fP The aabb collider 
.br
\fIcollider\fP The other collider 
.RE
.PP
\fBReturns\fP
.RS 4
true The 2 colliders collide 
.PP
false The 2 colliders do not collide 
.RE
.PP

.SS "bool mtrx::ColliderDetectionUtil::CapsuleCollisionOptions (const \fBCapsuleCollider\fP & capCollider, const \fBCollider\fP & collider)"

.PP
Collision algorithm options for capsule colliders @mtrx::CapsuleCollider\&. 
.PP
\fBParameters\fP
.RS 4
\fIcapCollider\fP The capsule collider 
.br
\fIcollider\fP The other collider 
.RE
.PP
\fBReturns\fP
.RS 4
true The 2 colliders collide 
.PP
false The 2 colliders do not collide 
.RE
.PP

.SS "bool mtrx::ColliderDetectionUtil::Collide (const \fBCollider\fP & collider1, const \fBCollider\fP & collider2)"

.PP
Check for whether 2 colliders collide\&. 
.PP
\fBParameters\fP
.RS 4
\fIcollider1\fP The first collider 
.br
\fIcollider2\fP The second collider 
.RE
.PP
\fBReturns\fP
.RS 4
true The 2 colliders collide 
.PP
false the 2 colliders do not collide 
.RE
.PP

.SS "bool mtrx::ColliderDetectionUtil::ConvexShapeCollisionOptions (const \fBConvexShapeCollider\fP & convexCollider, const \fBCollider\fP & collider)"

.PP
Collision algotithm options for convex shape colliders\&. 
.PP
\fBSee also\fP
.RS 4
\fBmtrx::ConvexShapeCollider\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fIconvexCollider\fP The convex shape collider 
.br
\fIcollider\fP The other collider 
.RE
.PP
\fBReturns\fP
.RS 4
true The 2 colliders collide 
.PP
false The 2 colliders do not collide 
.RE
.PP

.SS "bool mtrx::ColliderDetectionUtil::OOBBCollisionOptions (const \fBOOBBCollider\fP & oobb, const \fBCollider\fP & collider)"

.PP
Collision algorithm options for OOBB colliders\&. 
.PP
\fBSee also\fP
.RS 4
\fBmtrx::OOBBCollider\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fIoobb\fP The OOBB collider 
.br
\fIcollider\fP The other collider 
.RE
.PP
\fBReturns\fP
.RS 4
true The 2 colliders collide 
.PP
false The 2 colliders do not collide 
.RE
.PP

.SS "bool mtrx::ColliderDetectionUtil::SphereCollisionOptions (const \fBSphereCollider\fP & sphCollider, const \fBCollider\fP & collider)"

.PP
Collision algorithm options for sphere colliders\&. 
.PP
\fBSee also\fP
.RS 4
\fBmtrx::SphereCollider\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fIsphCollider\fP The sphere collider 
.br
\fIcollider\fP The other collider 
.RE
.PP
\fBReturns\fP
.RS 4
true The 2 colliders collide 
.PP
false The 2 colliders do not collide 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MTRX Engine from the source code\&.
