.TH "mtrx::IIntegratable" 3 "Sat Dec 7 2019" "MTRX Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtrx::IIntegratable \- Interface for integration PS: Not used that much really\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IIntegratable\&.h>\fP
.PP
Inherited by \fBmtrx::Body\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBIntegrate\fP (float deltaTime)=0"
.br
.RI "Integration functionality\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface for integration PS: Not used that much really\&. 


.SH "Member Function Documentation"
.PP 
.SS "virtual void mtrx::IIntegratable::Integrate (float deltaTime)\fC [pure virtual]\fP"

.PP
Integration functionality\&. 
.PP
\fBParameters\fP
.RS 4
\fIdeltaTime\fP Time elapsed from previous frame 
.RE
.PP

.PP
Implemented in \fBmtrx::Body\fP, and \fBmtrx::Rigidbody\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MTRX Engine from the source code\&.
