.TH "mtrx::RigidbodyManager" 3 "Sat Dec 7 2019" "MTRX Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtrx::RigidbodyManager \- Manager of rigidbodies\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RigidbodyManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRigidbodyManager\fP ()=default"
.br
.RI "Construct a new \fBRigidbody\fP Manager object\&. "
.ti -1c
.RI "\fB~RigidbodyManager\fP ()"
.br
.RI "Destroy the \fBRigidbody\fP Manager object\&. "
.ti -1c
.RI "void \fBIntegrate\fP (float deltaTime)"
.br
.RI "Integrate all entities of the game world\&. "
.ti -1c
.RI "void \fBIntegrateRigidbodies\fP (float deltaTime)"
.br
.RI "Integrate rigidbodies\&. "
.ti -1c
.RI "void \fBUpdateForces\fP (float deltaTime)"
.br
.RI "Update the forces applied to the rigidbodies by updating the force generators\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::unordered_map< \fBRigidbody\fP *, \fBrb_ForceGenerationRegistry\fP > \fBrigidbodyRegistry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Manager of rigidbodies\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "mtrx::RigidbodyManager::RigidbodyManager ()\fC [default]\fP"

.PP
Construct a new \fBRigidbody\fP Manager object\&. 
.SS "mtrx::RigidbodyManager::~RigidbodyManager ()"

.PP
Destroy the \fBRigidbody\fP Manager object\&. 
.SH "Member Function Documentation"
.PP 
.SS "void mtrx::RigidbodyManager::Integrate (float deltaTime)"

.PP
Integrate all entities of the game world\&. 
.PP
\fBParameters\fP
.RS 4
\fIdeltaTime\fP The time elapsed between frames 
.RE
.PP

.SS "void mtrx::RigidbodyManager::IntegrateRigidbodies (float deltaTime)"

.PP
Integrate rigidbodies\&. 
.PP
\fBParameters\fP
.RS 4
\fIdeltaTime\fP The time elapsed between frames 
.RE
.PP

.SS "void mtrx::RigidbodyManager::UpdateForces (float deltaTime)"

.PP
Update the forces applied to the rigidbodies by updating the force generators\&. 
.PP
\fBParameters\fP
.RS 4
\fIdeltaTime\fP The time elapsed between frames 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MTRX Engine from the source code\&.
