.TH "mtrx::ObjectAxes" 3 "Sat Dec 7 2019" "MTRX Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtrx::ObjectAxes \- The axes that define an objects world\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Defs\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "glm::vec3 & \fBoperator[]\fP (int index)"
.br
.ti -1c
.RI "const glm::vec3 & \fBoperator[]\fP (int index) const"
.br
.ti -1c
.RI "\fBObjectAxes\fP (const glm::vec3 &forward=glm::vec3(0, 0, \-1), const glm::vec3 &up=glm::vec3(0, 1, 0), const glm::vec3 &side=glm::vec3(1, 0, 0))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      glm::vec3 \fBside\fP"
.br
.ti -1c
.RI "      glm::vec3 \fBup\fP"
.br
.ti -1c
.RI "      glm::vec3 \fBforward\fP"
.br
.ti -1c
.RI "   } "
.br
.ti -1c
.RI "   glm::vec3 \fBaxes\fP [3]"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
The axes that define an objects world\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for MTRX Engine from the source code\&.
