.TH "mtrx::Ray" 3 "Sat Dec 7 2019" "MTRX Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtrx::Ray \- Implementation of a ray\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Ray\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRay\fP (const glm::vec3 &startPos=glm::vec3(), const glm::vec3 &rayDirection=glm::vec3())"
.br
.RI "Construct a new \fBRay\fP object\&. "
.ti -1c
.RI "\fB~Ray\fP ()=default"
.br
.RI "Destroy the \fBRay\fP object\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBstartPosition\fP"
.br
.ti -1c
.RI "glm::vec3 \fBdirection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of a ray\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "mtrx::Ray::Ray (const glm::vec3 & startPos = \fCglm::vec3()\fP, const glm::vec3 & rayDirection = \fCglm::vec3()\fP)\fC [inline]\fP"

.PP
Construct a new \fBRay\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIstartPos\fP The start position of the ray 
.br
\fIrayDirection\fP A normalized vector representing the direction of the ray 
.RE
.PP

.SS "mtrx::Ray::~Ray ()\fC [default]\fP"

.PP
Destroy the \fBRay\fP object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MTRX Engine from the source code\&.
