.TH "mtrx::Simplex" 3 "Sat Dec 7 2019" "MTRX Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtrx::Simplex \- Simplest shape that can encapsulate a point in 3d space Used within GJK collision detection algorithm\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Defs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBb\fP"
.br
.ti -1c
.RI "glm::vec3 \fBc\fP"
.br
.ti -1c
.RI "glm::vec3 \fBd\fP"
.br
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simplest shape that can encapsulate a point in 3d space Used within GJK collision detection algorithm\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for MTRX Engine from the source code\&.
