.TH "mtrx::IBoundingVolume" 3 "Sat Dec 7 2019" "MTRX Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtrx::IBoundingVolume \- Interface used to define a bounding volume that can be used in a Bounding volume Hierarchy\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IBoundingVolume\&.h>\fP
.PP
Inherited by \fBmtrx::AABBCollider\fP\fC [private]\fP, and \fBmtrx::SphereCollider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual float \fBGetSize\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface used to define a bounding volume that can be used in a Bounding volume Hierarchy\&. 


.PP
\fBSee also\fP
.RS 4
\fBmtrx::BVHNode\fP PS: This infrastructure is being reworked 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MTRX Engine from the source code\&.
