.TH "mtrx::PotentialCollision" 3 "Sat Dec 7 2019" "MTRX Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtrx::PotentialCollision \- Potential collisions struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BVHNode\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBody\fP * \fBbodies\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Potential collisions struct\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for MTRX Engine from the source code\&.
