/**
 * DEPRECATED DO NOT USE THIS
 */
#pragma once

#include <entities/Particle.h>
#include <ParticleCollisionResolver.h>
#include <forceGenerators/ParticleGenerators/p_ForceGenerationRegistry.h>
#include <ParticleCollision.h>
#include <ParticleCollisionGenerator.h>

namespace mtrx
{
	// A struct that holds all the force generators of a certain particle
	struct ParticleForceGenerators
	{
		Particle* particle;
		p_ForceGenerationRegistry* registry;
	};

	class ParticleManager
	{
	public:
		std::list<Particle> particles; // All the particles of the game world since we will have a dynamic amount of them we might need a dynamic structure
		std::list<ParticleCollision> particleCollisions; // These are the collision events generated by the collision handler and resolved by the resolver
		std::list<ParticleForceGenerators> forceGenerationRegistry; // Store the particles to force generators that they own
		std::list<std::shared_ptr<ParticleCollisionGenerator>> particleCollisionGenerators; // This will store all the collision generators
		ParticleCollisionResolver collisionResolver; // We will need a collision resolver system
		unsigned int maxContacts; // The maximum number of contacts that we will handle at a current frame
		unsigned int numIterations; // The number of iterations of resolutions that we want
		
		ParticleManager();
		ParticleManager(unsigned int maxContacts, unsigned int numIterations);
		~ParticleManager();

		// Generator contact collisions
		unsigned int GenerateCollisions();
		// Update call for each frame
		void PhysicsUpdate();
		// Updates all particles
		void UpdateParticles();
		// Updates all forces with all particles
		void UpdateForces();
	};
}
